const teamsData = [
    // 1. Al-Nassr FC
    {
        name: "Al-Nassr FC",
        isWeak: false,
        squad: [
            { n: "Cristiano Ronaldo", p: "FW", r: 86, v: "$15M", main: true },
            { n: "Sadio Mané", p: "FW", r: 84, v: "$15M", main: true },
            { n: "Kingsley Coman", p: "FW", r: 83, v: "$35M", main: true },
            { n: "João Félix", p: "FW", r: 80, v: "$30M", main: true },
            { n: "Aiman Yahya", p: "MF", r: 75, v: "$3M", main: true },
            { n: "Abdullah Al-Khaibari", p: "MF", r: 73, v: "$2M", main: true },
            { n: "Iñigo Martínez", p: "DF", r: 80, v: "$5M", main: true },
            { n: "Mohamed Simakan", p: "DF", r: 79, v: "$35M", main: true },
            { n: "Abdulelah Al-Amri", p: "DF", r: 73, v: "$2M", main: true },
            { n: "Sultan Al-Ghannam", p: "DF", r: 76, v: "$3M", main: true },
            { n: "Bento", p: "GK", r: 79, v: "$15M", main: true },
            { n: "Ângelo Gabriel", p: "FW", r: 75, v: "$15M", main: false },
            { n: "Abdulrahman Ghareeb", p: "FW", r: 74, v: "$3M", main: false },
            { n: "Abdullah Al-Hamdan", p: "FW", r: 71, v: "$1.5M", main: false },
            { n: "Mohammed Maran", p: "FW", r: 68, v: "$1M", main: false },
            { n: "Haroune Camara", p: "FW", r: 69, v: "$1M", main: false },
            { n: "Sami Al-Najei", p: "MF", r: 72, v: "$1.5M", main: false },
            { n: "Ali Al-Hassan", p: "MF", r: 68, v: "$1M", main: false },
            { n: "Abdulmalik Al Jaber", p: "MF", r: 66, v: "$800K", main: false },
            { n: "Nawaf Boushal", p: "DF", r: 70, v: "$1M", main: false },
            { n: "Salem Al Najdi", p: "DF", r: 67, v: "$800K", main: false },
            { n: "Nader Al Sharari", p: "DF", r: 66, v: "$500K", main: false },
            { n: "Saad Al Nasser", p: "DF", r: 67, v: "$700K", main: false },
            { n: "Nawaf Al-Aqidi", p: "GK", r: 72, v: "$2M", main: false },
            { n: "Raghid Al-Najjar", p: "GK", r: 64, v: "$500K", main: false }
        ]
    },

    // 2. AC Milan
    {
        name: "AC Milan",
        isWeak: false,
        squad: [
            { n: "Rafael Leão", p: "FW", r: 86, v: "$75M", main: true },
            { n: "Santiago Gimenez", p: "FW", r: 82, v: "$40M", main: true },
            { n: "Christian Pulisic", p: "MF", r: 83, v: "$50M", main: true },
            { n: "Luka Modric", p: "MF", r: 85, v: "$10M", main: true },
            { n: "Adrien Rabiot", p: "MF", r: 84, v: "$35M", main: true },
            { n: "Youssouf Fofana", p: "MF", r: 81, v: "$30M", main: true },
            { n: "Pervis Estupiñán", p: "DF", r: 80, v: "$30M", main: true },
            { n: "Fikayo Tomori", p: "DF", r: 83, v: "$32M", main: true },
            { n: "Strahinja Pavlovic", p: "DF", r: 79, v: "$25M", main: true },
            { n: "Mario Gila", p: "DF", r: 78, v: "$20M", main: true },
            { n: "Mike Maignan", p: "GK", r: 87, v: "$38M", main: true },
            { n: "Gonçalo Ramos", p: "FW", r: 80, v: "$45M", main: false },
            { n: "Christopher Nkunku", p: "FW", r: 83, v: "$50M", main: false },
            { n: "Samuel Chukwueze", p: "FW", r: 79, v: "$20M", main: false },
            { n: "Alexis Saelemaekers", p: "FW", r: 77, v: "$12M", main: false },
            { n: "Francesco Camarda", p: "FW", r: 70, v: "$10M", main: false },
            { n: "Ruben Loftus-Cheek", p: "MF", r: 80, v: "$25M", main: false },
            { n: "Samuele Ricci", p: "MF", r: 78, v: "$25M", main: false },
            { n: "Ismaël Bennacer", p: "MF", r: 82, v: "$28M", main: false },
            { n: "Yunus Musah", p: "MF", r: 76, v: "$18M", main: false },
            { n: "Ardon Jashari", p: "MF", r: 74, v: "$12M", main: false },
            { n: "Silvano Vos", p: "MF", r: 71, v: "$8M", main: false },
            { n: "Koni De Winter", p: "DF", r: 75, v: "$15M", main: false },
            { n: "Matteo Gabbia", p: "DF", r: 77, v: "$12M", main: false },
            { n: "Filippo Terracciano", p: "DF", r: 73, v: "$5M", main: false },
            { n: "Pietro Terracciano", p: "GK", r: 76, v: "$3M", main: false },
            { n: "Lorenzo Torriani", p: "GK", r: 65, v: "$1M", main: false }
        ]
    },

    // 3. Juventus
    {
        name: "Juventus",
        isWeak: false,
        squad: [
            { n: "D. Vlahović", p: "FW", r: 84, v: "$65M", main: true },
            { n: "Jonathan David", p: "FW", r: 81, v: "$45M", main: true },
            { n: "K. Yildiz", p: "FW", r: 78, v: "$40M", main: true },
            { n: "T. Koopmeiners", p: "MF", r: 83, v: "$55M", main: true },
            { n: "D. Luiz", p: "MF", r: 83, v: "$45M", main: true },
            { n: "K. Thuram", p: "MF", r: 79, v: "$35M", main: true },
            { n: "A. Cambiaso", p: "DF", r: 81, v: "$35M", main: true },
            { n: "G. Bremer", p: "DF", r: 86, v: "$60M", main: true },
            { n: "F. Gatti", p: "DF", r: 78, v: "$25M", main: true },
            { n: "Zeki Çelik", p: "DF", r: 75, v: "$12M", main: true },
            { n: "M. Di Gregorio", p: "GK", r: 82, v: "$20M", main: true },
            { n: "Randal Kolo Muani", p: "FW", r: 82, v: "$45M", main: false },
            { n: "N. González", p: "FW", r: 81, v: "$35M", main: false },
            { n: "F. Conceição", p: "FW", r: 78, v: "$22M", main: false },
            { n: "Jérémie Boga", p: "FW", r: 77, v: "$18M", main: false },
            { n: "Edon Zhegrova", p: "FW", r: 78, v: "$20M", main: false },
            { n: "A. Milik", p: "FW", r: 77, v: "$8M", main: false },
            { n: "M. Locatelli", p: "MF", r: 81, v: "$28M", main: false },
            { n: "W. McKennie", p: "MF", r: 77, v: "$20M", main: false },
            { n: "F. Miretti", p: "MF", r: 75, v: "$15M", main: false },
            { n: "Arthur", p: "MF", r: 76, v: "$10M", main: false },
            { n: "P. Kalulu", p: "DF", r: 78, v: "$20M", main: false },
            { n: "Lloyd Kelly", p: "DF", r: 76, v: "$16M", main: false },
            { n: "Juan Cabal", p: "DF", r: 73, v: "$10M", main: false },
            { n: "D. Rugani", p: "DF", r: 76, v: "$6M", main: false },
            { n: "M. Perin", p: "GK", r: 78, v: "$4M", main: false },
            { n: "C. Pinsoglio", p: "GK", r: 68, v: "$500K", main: false }
        ]
    },

    // 4. Paris Saint-Germain
    {
        name: "Paris Saint-Germain",
        isWeak: false,
        squad: [
            { n: "K. Kvaratskhelia", p: "FW", r: 86, v: "$85M", main: true },
            { n: "O. Dembélé", p: "FW", r: 86, v: "$60M", main: true },
            { n: "B. Barcola", p: "FW", r: 80, v: "$65M", main: true },
            { n: "Vitinha", p: "MF", r: 85, v: "$55M", main: true },
            { n: "João Neves", p: "MF", r: 81, v: "$60M", main: true },
            { n: "W. Zaïre-Emery", p: "MF", r: 81, v: "$60M", main: true },
            { n: "Nuno Mendes", p: "DF", r: 83, v: "$55M", main: true },
            { n: "Marquinhos", p: "DF", r: 87, v: "$50M", main: true },
            { n: "I. Zabarnyi", p: "DF", r: 80, v: "$42M", main: true },
            { n: "A. Hakimi", p: "DF", r: 84, v: "$60M", main: true },
            { n: "Lucas Chevalier", p: "GK", r: 82, v: "$35M", main: true },
            { n: "Désiré Doué", p: "FW", r: 78, v: "$40M", main: false },
            { n: "Quentin Ndjantou", p: "FW", r: 68, v: "$3M", main: false },
            { n: "Ibrahim Mbaye", p: "FW", r: 66, v: "$2M", main: false },
            { n: "Fabián Ruiz", p: "MF", r: 82, v: "$35M", main: false },
            { n: "Maghnes Akliouche", p: "MF", r: 78, v: "$30M", main: false },
            { n: "Senny Mayulu", p: "MF", r: 72, v: "$10M", main: false },
            { n: "Dro Fernández", p: "MF", r: 68, v: "$3M", main: false },
            { n: "Renato Sanches", p: "MF", r: 76, v: "$8M", main: false },
            { n: "Willian Pacho", p: "DF", r: 78, v: "$40M", main: false },
            { n: "Lucas Beraldo", p: "DF", r: 77, v: "$30M", main: false },
            { n: "Lucas Hernández", p: "DF", r: 82, v: "$35M", main: false },
            { n: "Yoram Zague", p: "DF", r: 69, v: "$4M", main: false },
            { n: "Matvei Safonov", p: "GK", r: 77, v: "$20M", main: false },
            { n: "Alessandro Longoni", p: "GK", r: 62, v: "$1M", main: false }
        ]
    },

    // 5. Deportivo La Coruña
    {
        name: "Deportivo La Coruña",
        isWeak: true,
        squad: [
            { n: "Yeremay Hernández", p: "FW", r: 74, v: "$8M", main: true },
            { n: "Zakaria Eddahchouri", p: "FW", r: 72, v: "$4M", main: true },
            { n: "David Mella", p: "FW", r: 73, v: "$6M", main: true },
            { n: "Mario Soriano", p: "MF", r: 74, v: "$4M", main: true },
            { n: "Diego Villares", p: "MF", r: 72, v: "$2M", main: true },
            { n: "Charlie Patino", p: "MF", r: 73, v: "$5M", main: true },
            { n: "Giacomo Quagliata", p: "DF", r: 72, v: "$3M", main: true },
            { n: "Arnau Comas", p: "DF", r: 71, v: "$2M", main: true },
            { n: "Dani Barcia", p: "DF", r: 70, v: "$2M", main: true },
            { n: "Miguel Loureiro", p: "DF", r: 71, v: "$2M", main: true },
            { n: "Álvaro Fernández", p: "GK", r: 73, v: "$3M", main: true },
            { n: "Luis Cruz", p: "FW", r: 69, v: "$1.5M", main: false },
            { n: "Bil Nsongo", p: "FW", r: 67, v: "$1M", main: false },
            { n: "Riki Rodríguez", p: "MF", r: 72, v: "$2.5M", main: false },
            { n: "José Ángel", p: "MF", r: 70, v: "$1M", main: false },
            { n: "Noé Carrillo", p: "MF", r: 66, v: "$800K", main: false },
            { n: "Lucas Noubi", p: "DF", r: 70, v: "$2M", main: false },
            { n: "Ximo Navarro", p: "DF", r: 69, v: "$800K", main: false },
            { n: "Germán Parreño", p: "GK", r: 68, v: "$500K", main: false },
            { n: "Eric Puerto", p: "GK", r: 66, v: "$400K", main: false }
        ]
    },

    // 6. Bayern München
    {
        name: "Bayern München",
        isWeak: false,
        squad: [
            { n: "Harry Kane", p: "FW", r: 89, v: "$90M", main: true },
            { n: "Luis Díaz", p: "FW", r: 84, v: "$75M", main: true },
            { n: "Michael Olise", p: "MF", r: 83, v: "$65M", main: true },
            { n: "Jamal Musiala", p: "MF", r: 88, v: "$130M", main: true },
            { n: "Joshua Kimmich", p: "MF", r: 86, v: "$50M", main: true },
            { n: "Aleksandar Pavlovic", p: "MF", r: 79, v: "$50M", main: true },
            { n: "Alphonso Davies", p: "DF", r: 82, v: "$50M", main: true },
            { n: "Jonathan Tah", p: "DF", r: 83, v: "$30M", main: true },
            { n: "Dayot Upamecano", p: "DF", r: 82, v: "$45M", main: true },
            { n: "Sacha Boey", p: "DF", r: 78, v: "$18M", main: true },
            { n: "Manuel Neuer", p: "GK", r: 85, v: "$5M", main: true },
            { n: "Serge Gnabry", p: "FW", r: 82, v: "$30M", main: false },
            { n: "Bryan Zaragoza", p: "FW", r: 77, v: "$12M", main: false },
            { n: "Armindo Sieb", p: "FW", r: 74, v: "$10M", main: false },
            { n: "Konrad Laimer", p: "MF", r: 82, v: "$30M", main: false },
            { n: "João Palhinha", p: "MF", r: 83, v: "$40M", main: false },
            { n: "Tom Bischof", p: "MF", r: 75, v: "$15M", main: false },
            { n: "Ismael Saibari", p: "MF", r: 78, v: "$18M", main: false },
            { n: "Arijon Ibrahimovic", p: "MF", r: 72, v: "$5M", main: false },
            { n: "Lennart Karl", p: "MF", r: 68, v: "$3M", main: false },
            { n: "Kim Min-Jae", p: "DF", r: 83, v: "$45M", main: false },
            { n: "Hiroki Ito", p: "DF", r: 79, v: "$25M", main: false },
            { n: "Josip Stanisic", p: "DF", r: 78, v: "$22M", main: false },
            { n: "Nathaniel Brown", p: "DF", r: 73, v: "$8M", main: false },
            { n: "Sven Ulreich", p: "GK", r: 74, v: "$1M", main: false },
            { n: "Jonas Urbig", p: "GK", r: 75, v: "$10M", main: false }
        ]
    },

    // 7. Real Madrid
    {
        name: "Real Madrid",
        isWeak: false,
        squad: [
            { n: "Kylian Mbappé", p: "FW", r: 91, v: "$180M", main: true },
            { n: "Vinícius Júnior", p: "FW", r: 90, v: "$180M", main: true },
            { n: "Rodrygo", p: "FW", r: 87, v: "$110M", main: true },
            { n: "Jude Bellingham", p: "MF", r: 90, v: "$180M", main: true },
            { n: "Federico Valverde", p: "MF", r: 88, v: "$130M", main: true },
            { n: "Aurélien Tchouaméni", p: "MF", r: 85, v: "$90M", main: true },
            { n: "Marc Cucurella", p: "DF", r: 82, v: "$30M", main: true },
            { n: "Antonio Rüdiger", p: "DF", r: 87, v: "$25M", main: true },
            { n: "Éder Militão", p: "DF", r: 85, v: "$60M", main: true },
            { n: "T. Alexander-Arnold", p: "DF", r: 86, v: "$70M", main: true },
            { n: "Thibaut Courtois", p: "GK", r: 89, v: "$28M", main: true },
            { n: "Endrick", p: "FW", r: 77, v: "$60M", main: false },
            { n: "Franco Mastantuono", p: "FW", r: 73, v: "$15M", main: false },
            { n: "Carlos Espí", p: "FW", r: 68, v: "$2M", main: false },
            { n: "Eduardo Camavinga", p: "MF", r: 85, v: "$100M", main: false },
            { n: "Arda Güler", p: "MF", r: 78, v: "$45M", main: false },
            { n: "Brahim Díaz", p: "MF", r: 82, v: "$40M", main: false },
            { n: "Bernardo Silva", p: "MF", r: 87, v: "$70M", main: false },
            { n: "Ibrahima Konaté", p: "DF", r: 83, v: "$45M", main: false },
            { n: "Dean Huijsen", p: "DF", r: 76, v: "$18M", main: false },
            { n: "Ferland Mendy", p: "DF", r: 82, v: "$22M", main: false },
            { n: "Denzel Dumfries", p: "DF", r: 81, v: "$25M", main: false },
            { n: "Raúl Asencio", p: "DF", r: 70, v: "$5M", main: false },
            { n: "Álvaro Carreras", p: "DF", r: 74, v: "$8M", main: false },
            { n: "Andriy Lunin", p: "GK", r: 81, v: "$25M", main: false }
        ]
    },

    // 8. FC Barcelona
    {
        name: "FC Barcelona",
        isWeak: false,
        squad: [
            { n: "Lamine Yamal", p: "FW", r: 87, v: "$150M", main: true },
            { n: "Raphinha", p: "FW", r: 84, v: "$60M", main: true },
            { n: "Anthony Gordon", p: "FW", r: 82, v: "$60M", main: true },
            { n: "Pedri", p: "MF", r: 86, v: "$80M", main: true },
            { n: "Gavi", p: "MF", r: 83, v: "$90M", main: true },
            { n: "Dani Olmo", p: "MF", r: 84, v: "$60M", main: true },
            { n: "Alejandro Balde", p: "DF", r: 81, v: "$50M", main: true },
            { n: "Pau Cubarsí", p: "DF", r: 79, v: "$40M", main: true },
            { n: "Ronald Araújo", p: "DF", r: 85, v: "$70M", main: true },
            { n: "Jules Koundé", p: "DF", r: 85, v: "$55M", main: true },
            { n: "Joan García", p: "GK", r: 80, v: "$25M", main: true },
            { n: "Karim Adeyemi", p: "FW", r: 80, v: "$35M", main: false },
            { n: "Ferran Torres", p: "FW", r: 80, v: "$30M", main: false },
            { n: "Roony Bardghji", p: "FW", r: 74, v: "$15M", main: false },
            { n: "Hamza Abdelkarim", p: "FW", r: 68, v: "$2M", main: false },
            { n: "Frenkie de Jong", p: "MF", r: 87, v: "$70M", main: false },
            { n: "Fermín López", p: "MF", r: 79, v: "$30M", main: false },
            { n: "Marc Casadó", p: "MF", r: 76, v: "$15M", main: false },
            { n: "Marc Bernal", p: "MF", r: 72, v: "$10M", main: false },
            { n: "Andreas Christensen", p: "DF", r: 82, v: "$30M", main: false },
            { n: "Eric García", p: "DF", r: 77, v: "$18M", main: false },
            { n: "Gerard Martín", p: "DF", r: 71, v: "$5M", main: false },
            { n: "Héctor Fort", p: "DF", r: 72, v: "$10M", main: false },
            { n: "Marc-André ter Stegen", p: "GK", r: 89, v: "$28M", main: false },
            { n: "Wojciech Szczesny", p: "GK", r: 80, v: "$3M", main: false }
        ]
    },

    // 9. Liverpool FC
    {
        name: "Liverpool FC",
        isWeak: false,
        squad: [
            { n: "Alexander Isak", p: "FW", r: 85, v: "$75M", main: true },
            { n: "Cody Gakpo", p: "FW", r: 83, v: "$55M", main: true },
            { n: "Hugo Ekitike", p: "FW", r: 79, v: "$35M", main: true },
            { n: "Florian Wirtz", p: "MF", r: 88, v: "$130M", main: true },
            { n: "Dominik Szoboszlai", p: "MF", r: 82, v: "$75M", main: true },
            { n: "Alexis Mac Allister", p: "MF", r: 85, v: "$75M", main: true },
            { n: "Milos Kerkez", p: "DF", r: 78, v: "$30M", main: true },
            { n: "Virgil van Dijk", p: "DF", r: 89, v: "$30M", main: true },
            { n: "Ibrahima Konaté", p: "DF", r: 83, v: "$45M", main: true },
            { n: "Jeremie Frimpong", p: "DF", r: 84, v: "$50M", main: true },
            { n: "Alisson Becker", p: "GK", r: 89, v: "$32M", main: true },
            { n: "Federico Chiesa", p: "FW", r: 82, v: "$35M", main: false },
            { n: "Víctor Muñoz", p: "FW", r: 68, v: "$2M", main: false },
            { n: "Lewis Koumas", p: "FW", r: 67, v: "$2M", main: false },
            { n: "Rio Ngumoha", p: "FW", r: 66, v: "$3M", main: false },
            { n: "Ryan Gravenberch", p: "MF", r: 80, v: "$40M", main: false },
            { n: "Curtis Jones", p: "MF", r: 80, v: "$35M", main: false },
            { n: "Harvey Elliott", p: "MF", r: 78, v: "$35M", main: false },
            { n: "Wataru Endo", p: "MF", r: 79, v: "$12M", main: false },
            { n: "Stefan Bajcetic", p: "MF", r: 74, v: "$15M", main: false },
            { n: "Trey Nyoni", p: "MF", r: 66, v: "$3M", main: false },
            { n: "Joe Gomez", p: "DF", r: 80, v: "$28M", main: false },
            { n: "Conor Bradley", p: "DF", r: 76, v: "$20M", main: false },
            { n: "Kostas Tsimikas", p: "DF", r: 77, v: "$18M", main: false },
            { n: "Jérémy Jacquet", p: "DF", r: 71, v: "$8M", main: false },
            { n: "Giovanni Leoni", p: "DF", r: 70, v: "$6M", main: false },
            { n: "Giorgi Mamardashvili", p: "GK", r: 83, v: "$45M", main: false },
            { n: "Freddie Woodman", p: "GK", r: 73, v: "$4M", main: false },
            { n: "Vitezslav Jaros", p: "GK", r: 70, v: "$3M", main: false }
        ]
    },

    // 10. Ipswich Town
    {
        name: "Ipswich Town",
        isWeak: true,
        squad: [
            { n: "Jack Clarke", p: "FW", r: 76, v: "$18M", main: true },
            { n: "Jaden Philogene", p: "FW", r: 75, v: "$15M", main: true },
            { n: "Chuba Akpom", p: "FW", r: 74, v: "$8M", main: true },
            { n: "Florentino", p: "MF", r: 77, v: "$20M", main: true },
            { n: "Azor Matusiwa", p: "MF", r: 76, v: "$14M", main: true },
            { n: "Jack Taylor", p: "MF", r: 72, v: "$5M", main: true },
            { n: "Leif Davis", p: "DF", r: 74, v: "$12M", main: true },
            { n: "Jacob Greaves", p: "DF", r: 75, v: "$15M", main: true },
            { n: "Issa Diop", p: "DF", r: 76, v: "$16M", main: true },
            { n: "Ben Johnson", p: "DF", r: 73, v: "$8M", main: true },
            { n: "Alex Palmer", p: "GK", r: 74, v: "$6M", main: true },
            { n: "George Hirst", p: "FW", r: 71, v: "$4M", main: false },
            { n: "Ali Al-Hamadi", p: "FW", r: 70, v: "$3M", main: false },
            { n: "Daizen Maeda", p: "FW", r: 75, v: "$10M", main: false },
            { n: "Fatawu Issahaku", p: "FW", r: 74, v: "$12M", main: false },
            { n: "Chiedozie Ogbene", p: "FW", r: 73, v: "$6M", main: false },
            { n: "Emersonn", p: "FW", r: 68, v: "$2M", main: false },
            { n: "Sindre Walle Egeli", p: "FW", r: 67, v: "$2M", main: false },
            { n: "Marcelino Núñez", p: "MF", r: 74, v: "$8M", main: false },
            { n: "Anis Mehmeti", p: "MF", r: 72, v: "$5M", main: false },
            { n: "Kasey McAteer", p: "MF", r: 71, v: "$4M", main: false },
            { n: "Cameron Humphreys", p: "MF", r: 68, v: "$2M", main: false },
            { n: "Dara O'Shea", p: "DF", r: 74, v: "$10M", main: false },
            { n: "Cedric Kipre", p: "DF", r: 73, v: "$6M", main: false },
            { n: "Darnell Furlong", p: "DF", r: 73, v: "$6M", main: false },
            { n: "Harrison Clarke", p: "DF", r: 71, v: "$4M", main: false },
            { n: "Kjell Scherpen", p: "GK", r: 72, v: "$4M", main: false },
            { n: "Christian Walton", p: "GK", r: 71, v: "$2M", main: false },
            { n: "David Button", p: "GK", r: 67, v: "$500K", main: false },
            { n: "Kayne Van Oevelen", p: "GK", r: 64, v: "$400K", main: false }
        ]
    },

    // 11. Manchester City
    {
        name: "Manchester City",
        isWeak: false,
        squad: [
            { n: "Erling Haaland", p: "FW", r: 91, v: "$180M", main: true },
            { n: "Jérémy Doku", p: "FW", r: 83, v: "$65M", main: true },
            { n: "Omar Marmoush", p: "FW", r: 81, v: "$40M", main: true },
            { n: "Phil Foden", p: "MF", r: 88, v: "$130M", main: true },
            { n: "Rodri", p: "MF", r: 91, v: "$130M", main: true },
            { n: "Tijjani Reijnders", p: "MF", r: 84, v: "$50M", main: true },
            { n: "Rayan Aït-Nouri", p: "DF", r: 81, v: "$35M", main: true },
            { n: "Rúben Dias", p: "DF", r: 88, v: "$80M", main: true },
            { n: "Josko Gvardiol", p: "DF", r: 84, v: "$75M", main: true },
            { n: "Marc Guéhi", p: "DF", r: 82, v: "$45M", main: true },
            { n: "Gianluigi Donnarumma", p: "GK", r: 89, v: "$40M", main: true },
            { n: "Savinho", p: "FW", r: 80, v: "$50M", main: false },
            { n: "Antoine Semenyo", p: "FW", r: 77, v: "$20M", main: false },
            { n: "Divin Mubama", p: "FW", r: 69, v: "$3M", main: false },
            { n: "Jaden Heskey", p: "FW", r: 67, v: "$2M", main: false },
            { n: "Jeremy Monga", p: "FW", r: 65, v: "$1M", main: false },
            { n: "Ryan McAidoo", p: "FW", r: 66, v: "$2M", main: false },
            { n: "Claudio Echeverri", p: "MF", r: 74, v: "$18M", main: false },
            { n: "Rayan Cherki", p: "MF", r: 79, v: "$30M", main: false },
            { n: "Mateo Kovacic", p: "MF", r: 82, v: "$25M", main: false },
            { n: "Nico González", p: "MF", r: 78, v: "$25M", main: false },
            { n: "Matheus Nunes", p: "MF", r: 79, v: "$35M", main: false },
            { n: "Jack Grealish", p: "MF", r: 83, v: "$45M", main: false },
            { n: "Elliot Anderson", p: "MF", r: 76, v: "$20M", main: false },
            { n: "Kalvin Phillips", p: "MF", r: 75, v: "$12M", main: false },
            { n: "Divine Mukasa", p: "MF", r: 66, v: "$2M", main: false },
            { n: "Floyd Samba", p: "MF", r: 65, v: "$1M", main: false },
            { n: "Rico Lewis", p: "DF", r: 77, v: "$30M", main: false },
            { n: "Vitor Reis", p: "DF", r: 72, v: "$10M", main: false },
            { n: "Abdukodir Khusanov", p: "DF", r: 74, v: "$12M", main: false },
            { n: "Nico O'Reilly", p: "DF", r: 70, v: "$5M", main: false },
            { n: "Issa Kaboré", p: "DF", r: 73, v: "$8M", main: false },
            { n: "Juma Bah", p: "DF", r: 68, v: "$3M", main: false },
            { n: "Stephen Mfuni", p: "DF", r: 66, v: "$2M", main: false },
            { n: "Kaden Braithwaite", p: "DF", r: 65, v: "$1M", main: false },
            { n: "Finley Burns", p: "DF", r: 68, v: "$2M", main: false },
            { n: "Josh Wilson-Esbrand", p: "DF", r: 70, v: "$4M", main: false },
            { n: "Marcus Bettinelli", p: "GK", r: 70, v: "$2M", main: false }
        ]
    },

    // 12. Hamburger SV
    {
        name: "Hamburger SV",
        isWeak: true,
        squad: [
            { n: "Patson Daka", p: "FW", r: 75, v: "$10M", main: true },
            { n: "Rayan Philippe", p: "FW", r: 74, v: "$8M", main: true },
            { n: "Yussuf Poulsen", p: "FW", r: 75, v: "$6M", main: true },
            { n: "Albert Sambi Lokonga", p: "MF", r: 76, v: "$12M", main: true },
            { n: "Albert Grønbaek", p: "MF", r: 75, v: "$10M", main: true },
            { n: "Nicolás Capaldo", p: "MF", r: 74, v: "$8M", main: true },
            { n: "Miro Muheim", p: "DF", r: 74, v: "$6M", main: true },
            { n: "Mario Vuskovic", p: "DF", r: 75, v: "$8M", main: true },
            { n: "Warmed Omari", p: "DF", r: 74, v: "$6M", main: true },
            { n: "Jordan Torunarigha", p: "DF", r: 73, v: "$5M", main: true },
            { n: "Daniel Heuer Fernandes", p: "GK", r: 74, v: "$3M", main: true },
            { n: "Jean-Luc Dompé", p: "FW", r: 73, v: "$4M", main: false },
            { n: "Emir Sahiti", p: "FW", r: 72, v: "$3M", main: false },
            { n: "Fabio Baldé", p: "FW", r: 70, v: "$3M", main: false },
            { n: "Alexander Røssing-Lelesiit", p: "FW", r: 67, v: "$2M", main: false },
            { n: "Otto Stange", p: "FW", r: 66, v: "$1.5M", main: false },
            { n: "Immanuel Pherai", p: "MF", r: 73, v: "$5M", main: false },
            { n: "Bakery Jatta", p: "MF", r: 72, v: "$4M", main: false },
            { n: "Nicolai Remberg", p: "MF", r: 72, v: "$4M", main: false },
            { n: "Martin Adeline", p: "MF", r: 71, v: "$3M", main: false },
            { n: "Bilal Nadir", p: "MF", r: 70, v: "$2.5M", main: false },
            { n: "Kofi Amoako", p: "MF", r: 67, v: "$1M", main: false },
            { n: "Daniel Elfadli", p: "DF", r: 72, v: "$3M", main: false },
            { n: "Joel Agyekum", p: "DF", r: 68, v: "$1.5M", main: false },
            { n: "Louis Lemke", p: "DF", r: 64, v: "$500K", main: false },
            { n: "Shafiq Nandja", p: "DF", r: 64, v: "$500K", main: false },
            { n: "Sander Tangvik", p: "GK", r: 71, v: "$2.5M", main: false },
            { n: "Fernando Dickes", p: "GK", r: 63, v: "$300K", main: false }
        ]
    },

    // 13. Hellas Verona
    {
        name: "Hellas Verona",
        isWeak: true,
        squad: [
            { n: "Amin Sarr", p: "FW", r: 74, v: "$6M", main: true },
            { n: "Daniel Mosquera", p: "FW", r: 73, v: "$4M", main: true },
            { n: "Dailon Livramento", p: "FW", r: 72, v: "$3M", main: true },
            { n: "Tomás Suslov", p: "MF", r: 76, v: "$12M", main: true },
            { n: "Suat Serdar", p: "MF", r: 76, v: "$10M", main: true },
            { n: "Grigoris Kastanos", p: "MF", r: 74, v: "$6M", main: true },
            { n: "Domagoj Bradaric", p: "DF", r: 75, v: "$7M", main: true },
            { n: "Pol Lirola", p: "DF", r: 74, v: "$5M", main: true },
            { n: "Seid Korac", p: "DF", r: 72, v: "$3M", main: true },
            { n: "Tobias Slotsager", p: "DF", r: 72, v: "$4M", main: true },
            { n: "Lorenzo Montipò", p: "GK", r: 76, v: "$6M", main: true },
            { n: "Samuele Mulattieri", p: "FW", r: 73, v: "$5M", main: false },
            { n: "Juan Cruz", p: "FW", r: 71, v: "$3M", main: false },
            { n: "Isaac", p: "FW", r: 70, v: "$2M", main: false },
            { n: "Kacper Sezonienko", p: "FW", r: 69, v: "$1.5M", main: false },
            { n: "Ioan Vermesan", p: "FW", r: 66, v: "$1M", main: false },
            { n: "Federico Caia", p: "FW", r: 65, v: "$800K", main: false },
            { n: "Salvatore Cerbone", p: "FW", r: 64, v: "$500K", main: false },
            { n: "Abdou Harroui", p: "MF", r: 74, v: "$5M", main: false },
            { n: "Antoine Bernede", p: "MF", r: 73, v: "$4M", main: false },
            { n: "Jean-Daniel Akpa Akpro", p: "MF", r: 73, v: "$3M", main: false },
            { n: "Roberto Gagliardini", p: "MF", r: 74, v: "$4M", main: false },
            { n: "Cheikh Niasse", p: "MF", r: 72, v: "$3M", main: false },
            { n: "Mattia Compagnon", p: "MF", r: 71, v: "$2.5M", main: false },
            { n: "Charlys", p: "MF", r: 70, v: "$2M", main: false },
            { n: "Leorat Bega", p: "MF", r: 67, v: "$1M", main: false },
            { n: "Ruben Akalé", p: "MF", r: 66, v: "$800K", main: false },
            { n: "Luca Szimionas", p: "MF", r: 65, v: "$600K", main: false },
            { n: "Jurgen Peci", p: "MF", r: 64, v: "$500K", main: false },
            { n: "Luca Monticelli", p: "MF", r: 66, v: "$800K", main: false },
            { n: "Martin Frese", p: "DF", r: 73, v: "$4M", main: false },
            { n: "Rafik Belghali", p: "DF", r: 72, v: "$3M", main: false },
            { n: "Andrias Edmundsson", p: "DF", r: 70, v: "$2M", main: false },
            { n: "Christian Corradi", p: "DF", r: 69, v: "$1.5M", main: false },
            { n: "Daniel Oyegoke", p: "DF", r: 70, v: "$2M", main: false },
            { n: "Andrej Popovic", p: "DF", r: 67, v: "$1M", main: false },
            { n: "Fallou Cham", p: "DF", r: 66, v: "$800K", main: false },
            { n: "Davide De Battisti", p: "DF", r: 65, v: "$600K", main: false },
            { n: "William Feola", p: "DF", r: 65, v: "$600K", main: false },
            { n: "Nicolò Calabrese", p: "DF", r: 64, v: "$500K", main: false },
            { n: "Nicola Leali", p: "GK", r: 73, v: "$2M", main: false },
            { n: "Simone Perilli", p: "GK", r: 70, v: "$1M", main: false },
            { n: "Arthur Borghi", p: "GK", r: 64, v: "$400K", main: false },
            { n: "Mirko Castagnini", p: "GK", r: 63, v: "$300K", main: false },
            { n: "Giacomo Toniolo", p: "GK", r: 65, v: "$500K", main: false }
        ]
    },

    // 14. RC Strasbourg Alsace
    {
        name: "RC Strasbourg Alsace",
        isWeak: true,
        squad: [
            { n: "Sékou Mara", p: "FW", r: 75, v: "$8M", main: true },
            { n: "Julio Enciso", p: "FW", r: 76, v: "$14M", main: true },
            { n: "Sebastian Nanasi", p: "FW", r: 75, v: "$10M", main: true },
            { n: "Giovanni Reyna", p: "MF", r: 76, v: "$12M", main: true },
            { n: "Mathis Amougou", p: "MF", r: 73, v: "$5M", main: true },
            { n: "Maximillian Oyedele", p: "MF", r: 72, v: "$4M", main: true },
            { n: "Ben Chilwell", p: "DF", r: 77, v: "$15M", main: true },
            { n: "Abakar Sylla", p: "DF", r: 75, v: "$8M", main: true },
            { n: "Ismael Doukoure", p: "DF", r: 75, v: "$9M", main: true },
            { n: "Guela Doué", p: "DF", r: 74, v: "$7M", main: true },
            { n: "Milosz Piekutowski", p: "GK", r: 70, v: "$2M", main: true },
            { n: "Joaquín Panichelli", p: "FW", r: 73, v: "$5M", main: false },
            { n: "Diego Moreira", p: "FW", r: 73, v: "$6M", main: false },
            { n: "Milos Lukovic", p: "FW", r: 72, v: "$4M", main: false },
            { n: "Martial Godo", p: "FW", r: 71, v: "$3M", main: false },
            { n: "Samuel Amo-Ameyaw", p: "FW", r: 70, v: "$3M", main: false },
            { n: "Rayane Messi", p: "FW", r: 68, v: "$2M", main: false },
            { n: "Gessime Yassine", p: "FW", r: 67, v: "$1.5M", main: false },
            { n: "Pape Diop", p: "MF", r: 72, v: "$3.5M", main: false },
            { n: "Pape Diong", p: "MF", r: 70, v: "$2.5M", main: false },
            { n: "Samir El Mourabet", p: "MF", r: 69, v: "$2M", main: false },
            { n: "Diogo Sousa", p: "MF", r: 68, v: "$1.5M", main: false },
            { n: "Rabby Nzingoula", p: "MF", r: 68, v: "$1.5M", main: false },
            { n: "Abdoul Ouattara", p: "MF", r: 67, v: "$1M", main: false },
            { n: "Benjamin Brantlind", p: "MF", r: 65, v: "$800K", main: false },
            { n: "Saïdou Sow", p: "DF", r: 74, v: "$6M", main: false },
            { n: "Andrew Omobamidele", p: "DF", r: 73, v: "$5M", main: false },
            { n: "Soumaila Coulibaly", p: "DF", r: 72, v: "$4M", main: false },
            { n: "Mateo Del Blanco", p: "DF", r: 71, v: "$3M", main: false },
            { n: "Lucas Høgsberg", p: "DF", r: 70, v: "$2.5M", main: false },
            { n: "Yoni Gomis", p: "DF", r: 69, v: "$2M", main: false },
            { n: "Genesis Antwi", p: "DF", r: 66, v: "$1M", main: false }
        ]
    },

    // 15. Arsenal
    {
        name: "Arsenal",
        isWeak: false,
        squad: [
            { n: "Viktor Gyökeres", p: "FW", r: 85, v: "$75M", main: true },
            { n: "Bukayo Saka", p: "FW", r: 88, v: "$140M", main: true },
            { n: "Gabriel Martinelli", p: "FW", r: 83, v: "$60M", main: true },
            { n: "Martin Ødegaard", p: "MF", r: 88, v: "$110M", main: true },
            { n: "Declan Rice", p: "MF", r: 87, v: "$110M", main: true },
            { n: "Martín Zubimendi", p: "MF", r: 84, v: "$55M", main: true },
            { n: "Piero Hincapié", p: "DF", r: 82, v: "$45M", main: true },
            { n: "William Saliba", p: "DF", r: 88, v: "$80M", main: true },
            { n: "Gabriel Magalhães", p: "DF", r: 86, v: "$75M", main: true },
            { n: "Ben White", p: "DF", r: 84, v: "$55M", main: true },
            { n: "David Raya", p: "GK", r: 85, v: "$40M", main: true },
            { n: "Kai Havertz", p: "FW", r: 83, v: "$60M", main: false },
            { n: "Gabriel Jesus", p: "FW", r: 82, v: "$45M", main: false },
            { n: "Noni Madueke", p: "FW", r: 79, v: "$35M", main: false },
            { n: "Christos Tzolis", p: "FW", r: 77, v: "$20M", main: false },
            { n: "Reiss Nelson", p: "FW", r: 76, v: "$15M", main: false },
            { n: "Eberechi Eze", p: "MF", r: 82, v: "$55M", main: false },
            { n: "Mikel Merino", p: "MF", r: 82, v: "$35M", main: false },
            { n: "Fabio Vieira", p: "MF", r: 77, v: "$22M", main: false },
            { n: "Ethan Nwaneri", p: "MF", r: 76, v: "$25M", main: false },
            { n: "Riccardo Calafiori", p: "DF", r: 81, v: "$45M", main: false },
            { n: "Jurriën Timber", p: "DF", r: 81, v: "$40M", main: false },
            { n: "Cristhian Mosquera", p: "DF", r: 78, v: "$30M", main: false },
            { n: "Myles Lewis-Skelly", p: "DF", r: 72, v: "$10M", main: false },
            { n: "Kepa Arrizabalaga", p: "GK", r: 78, v: "$10M", main: false },
            { n: "Illan Meslier", p: "GK", r: 76, v: "$15M", main: false },
            { n: "Tommy Setford", p: "GK", r: 66, v: "$2M", main: false }
        ]
    },

    // 16. Chelsea
    {
        name: "Chelsea",
        isWeak: false,
        squad: [
            { n: "Nicolas Jackson", p: "FW", r: 82, v: "$50M", main: true },
            { n: "Cole Palmer", p: "MF", r: 87, v: "$110M", main: true },
            { n: "Pedro Neto", p: "FW", r: 82, v: "$55M", main: true },
            { n: "Enzo Fernández", p: "MF", r: 84, v: "$75M", main: true },
            { n: "Moisés Caicedo", p: "MF", r: 85, v: "$80M", main: true },
            { n: "Romeo Lavia", p: "MF", r: 79, v: "$35M", main: true },
            { n: "Levi Colwill", p: "DF", r: 81, v: "$50M", main: true },
            { n: "Wesley Fofana", p: "DF", r: 80, v: "$40M", main: true },
            { n: "Benoît Badiashile", p: "DF", r: 79, v: "$30M", main: true },
            { n: "Reece James", p: "DF", r: 84, v: "$50M", main: true },
            { n: "Robert Sánchez", p: "GK", r: 80, v: "$25M", main: true },
            { n: "João Pedro", p: "FW", r: 80, v: "$45M", main: false },
            { n: "Liam Delap", p: "FW", r: 78, v: "$25M", main: false },
            { n: "Jamie Gittens", p: "FW", r: 78, v: "$30M", main: false },
            { n: "Estêvão", p: "FW", r: 77, v: "$40M", main: false },
            { n: "Danny Welbeck", p: "FW", r: 77, v: "$5M", main: false },
            { n: "Marc Guiu", p: "FW", r: 72, v: "$10M", main: false },
            { n: "Emmanuel Emegha", p: "FW", r: 74, v: "$15M", main: false },
            { n: "David Datro Fofana", p: "FW", r: 75, v: "$12M", main: false },
            { n: "Ryan Kavuma-Mcqueen", p: "FW", r: 64, v: "$1M", main: false },
            { n: "Dastan Satpaev", p: "FW", r: 64, v: "$1M", main: false },
            { n: "Morgan Rogers", p: "MF", r: 80, v: "$35M", main: false },
            { n: "Mykhailo Mudryk", p: "MF", r: 78, v: "$35M", main: false },
            { n: "Jordan Henderson", p: "MF", r: 76, v: "$3M", main: false },
            { n: "Valentín Barco", p: "MF", r: 76, v: "$15M", main: false },
            { n: "Dário Essugo", p: "MF", r: 74, v: "$12M", main: false },
            { n: "Geovany Quenda", p: "MF", r: 75, v: "$20M", main: false },
            { n: "Omari Kellyman", p: "MF", r: 69, v: "$5M", main: false },
            { n: "Reggie Walsh", p: "MF", r: 64, v: "$1M", main: false },
            { n: "Reggie Watson", p: "MF", r: 63, v: "$800K", main: false },
            { n: "Mahdi Nicoll-Jazuli", p: "MF", r: 63, v: "$800K", main: false },
            { n: "Malo Gusto", p: "DF", r: 80, v: "$35M", main: false },
            { n: "Jorrel Hato", p: "DF", r: 78, v: "$30M", main: false },
            { n: "Axel Disasi", p: "DF", r: 78, v: "$25M", main: false },
            { n: "Tosin Adarabioyo", p: "DF", r: 78, v: "$20M", main: false },
            { n: "Trevoh Chalobah", p: "DF", r: 78, v: "$20M", main: false },
            { n: "Maxence Lacroix", p: "DF", r: 78, v: "$22M", main: false },
            { n: "Aaron Anselmino", p: "DF", r: 73, v: "$8M", main: false },
            { n: "Mamadou Sarr", p: "DF", r: 71, v: "$5M", main: false },
            { n: "Marco Palestra", p: "DF", r: 72, v: "$6M", main: false },
            { n: "Josh Acheampong", p: "DF", r: 68, v: "$3M", main: false },
            { n: "Olutayo Subuloye", p: "DF", r: 63, v: "$800K", main: false },
            { n: "Calvin Diakite", p: "DF", r: 62, v: "$600K", main: false },
            { n: "Landon Emenalo", p: "DF", r: 63, v: "$800K", main: false },
            { n: "Filip Jørgensen", p: "GK", r: 76, v: "$15M", main: false },
            { n: "Gaga Slonina", p: "GK", r: 73, v: "$6M", main: false },
            { n: "Mike Penders", p: "GK", r: 70, v: "$5M", main: false },
            { n: "Teddy Sharman-Lowe", p: "GK", r: 67, v: "$2M", main: false },
            { n: "Ted Curd", p: "GK", r: 64, v: "$1M", main: false }
        ]
    },

    // 17. Manchester United
    {
        name: "Manchester United",
        isWeak: false,
        squad: [
            { n: "Benjamin Sesko", p: "FW", r: 83, v: "$65M", main: true },
            { n: "Marcus Rashford", p: "FW", r: 83, v: "$55M", main: true },
            { n: "Bryan Mbeumo", p: "FW", r: 82, v: "$50M", main: true },
            { n: "Bruno Fernandes", p: "MF", r: 87, v: "$65M", main: true },
            { n: "Kobbie Mainoo", p: "MF", r: 82, v: "$55M", main: true },
            { n: "Manuel Ugarte", p: "MF", r: 82, v: "$45M", main: true },
            { n: "Lisandro Martínez", p: "DF", r: 84, v: "$50M", main: true },
            { n: "Matthijs de Ligt", p: "DF", r: 84, v: "$50M", main: true },
            { n: "Diogo Dalot", p: "DF", r: 82, v: "$40M", main: true },
            { n: "Noussair Mazraoui", p: "DF", r: 81, v: "$30M", main: true },
            { n: "Senne Lammens", p: "GK", r: 77, v: "$18M", main: true },
            { n: "Matheus Cunha", p: "FW", r: 82, v: "$45M", main: false },
            { n: "Joshua Zirkzee", p: "FW", r: 79, v: "$35M", main: false },
            { n: "Amad Diallo", p: "FW", r: 79, v: "$30M", main: false },
            { n: "Ethan Wheatley", p: "FW", r: 68, v: "$3M", main: false },
            { n: "Shea Lacey", p: "FW", r: 67, v: "$3M", main: false },
            { n: "Ethan Williams", p: "FW", r: 65, v: "$1.5M", main: false },
            { n: "Enzo Kana-Biyik", p: "FW", r: 66, v: "$2M", main: false },
            { n: "JJ Gabriel", p: "FW", r: 64, v: "$1M", main: false },
            { n: "Mason Mount", p: "MF", r: 80, v: "$35M", main: false },
            { n: "Youri Tielemans", p: "MF", r: 81, v: "$35M", main: false },
            { n: "Andrey Santos", p: "MF", r: 78, v: "$25M", main: false },
            { n: "Toby Collyer", p: "MF", r: 71, v: "$5M", main: false },
            { n: "Daniel Gore", p: "MF", r: 70, v: "$4M", main: false },
            { n: "Jack Fletcher", p: "MF", r: 67, v: "$2M", main: false },
            { n: "Tyler Fletcher", p: "MF", r: 67, v: "$2M", main: false },
            { n: "Jim Thwaites", p: "MF", r: 64, v: "$1M", main: false },
            { n: "Jacob Devaney", p: "MF", r: 64, v: "$1M", main: false },
            { n: "Leny Yoro", p: "DF", r: 80, v: "$45M", main: false },
            { n: "Harry Maguire", p: "DF", r: 79, v: "$15M", main: false },
            { n: "Luke Shaw", p: "DF", r: 80, v: "$20M", main: false },
            { n: "Patrick Dorgu", p: "DF", r: 76, v: "$20M", main: false },
            { n: "Harry Amass", p: "DF", r: 70, v: "$5M", main: false },
            { n: "Ayden Heaven", p: "DF", r: 69, v: "$4M", main: false },
            { n: "Diego León", p: "DF", r: 69, v: "$4M", main: false },
            { n: "Jaydan Kamason", p: "DF", r: 65, v: "$1.5M", main: false },
            { n: "Daniel Armer", p: "DF", r: 64, v: "$1M", main: false },
            { n: "Karl Darlow", p: "GK", r: 74, v: "$3M", main: false },
            { n: "Tom Heaton", p: "GK", r: 71, v: "$1M", main: false },
            { n: "Radek Vítek", p: "GK", r: 70, v: "$3M", main: false },
            { n: "Dermot Mee", p: "GK", r: 64, v: "$800K", main: false }
        ]
    },

    // 18. Inter Milan
    {
        name: "Inter Milan",
        isWeak: false,
        squad: [
            { n: "Lautaro Martínez", p: "FW", r: 89, v: "$110M", main: true },
            { n: "Marcus Thuram", p: "FW", r: 84, v: "$65M", main: true },
            { n: "Nicolò Barella", p: "MF", r: 87, v: "$80M", main: true },
            { n: "Hakan Çalhanoglu", p: "MF", r: 85, v: "$45M", main: true },
            { n: "Piotr Zielinski", p: "MF", r: 82, v: "$25M", main: true },
            { n: "Federico Dimarco", p: "DF", r: 85, v: "$50M", main: true },
            { n: "Alessandro Bastoni", p: "DF", r: 87, v: "$70M", main: true },
            { n: "Benjamin Pavard", p: "DF", r: 83, v: "$40M", main: true },
            { n: "John Stones", p: "DF", r: 85, v: "$35M", main: true },
            { n: "Manuel Akanji", p: "DF", r: 82, v: "$30M", main: true },
            { n: "Ivan Provedel", p: "GK", r: 82, v: "$18M", main: true },
            { n: "Ange-Yoan Bonny", p: "FW", r: 76, v: "$20M", main: false },
            { n: "Luis Henrique", p: "FW", r: 77, v: "$20M", main: false },
            { n: "Pio Esposito", p: "FW", r: 74, v: "$12M", main: false },
            { n: "Mattia Mosconi", p: "FW", r: 67, v: "$2M", main: false },
            { n: "Matteo Lavelli", p: "FW", r: 66, v: "$1.5M", main: false },
            { n: "Jamal Iddrissou", p: "FW", r: 64, v: "$1M", main: false },
            { n: "Davide Frattesi", p: "MF", r: 82, v: "$35M", main: false },
            { n: "Henrikh Mkhitaryan", p: "MF", r: 81, v: "$10M", main: false },
            { n: "Kristjan Asllani", p: "MF", r: 78, v: "$20M", main: false },
            { n: "Petar Sucic", p: "MF", r: 76, v: "$15M", main: false },
            { n: "Andy Diouf", p: "MF", r: 77, v: "$18M", main: false },
            { n: "Aleksandar Stankovic", p: "MF", r: 73, v: "$8M", main: false },
            { n: "Yanis Massolin", p: "MF", r: 71, v: "$4M", main: false },
            { n: "Luka Topalovic", p: "MF", r: 68, v: "$3M", main: false },
            { n: "Yann Bisseck", p: "DF", r: 79, v: "$25M", main: false },
            { n: "Carlos Augusto", p: "DF", r: 79, v: "$22M", main: false },
            { n: "Yvan Maye", p: "DF", r: 68, v: "$2M", main: false },
            { n: "Leonardo Bovio", p: "DF", r: 64, v: "$1M", main: false },
            { n: "Mattia Marello", p: "DF", r: 64, v: "$1M", main: false },
            { n: "Josep Martínez", p: "GK", r: 77, v: "$10M", main: false },
            { n: "Raffaele Di Gennaro", p: "GK", r: 69, v: "$1M", main: false },
            { n: "Matteo Farronato", p: "GK", r: 63, v: "$500K", main: false }
        ]
    },

    // 19. Inter Miami CF
    {
        name: "Inter Miami CF",
        isWeak: false,
        squad: [
            { n: "Lionel Messi", p: "FW", r: 88, v: "$25M", main: true },
            { n: "Luis Suárez", p: "FW", r: 82, v: "$4M", main: true },
            { n: "Germán Berterame", p: "FW", r: 77, v: "$8M", main: true },
            { n: "Rodrigo De Paul", p: "MF", r: 84, v: "$30M", main: true },
            { n: "Casemiro", p: "MF", r: 82, v: "$10M", main: true },
            { n: "Telasco Segovia", p: "MF", r: 74, v: "$5M", main: true },
            { n: "Sergio Reguilón", p: "DF", r: 76, v: "$8M", main: true },
            { n: "Maximiliano Falcón", p: "DF", r: 74, v: "$3M", main: true },
            { n: "Gonzalo Luján", p: "DF", r: 73, v: "$4M", main: true },
            { n: "Facundo Mura", p: "DF", r: 74, v: "$4M", main: true },
            { n: "Dayne St. Clair", p: "GK", r: 74, v: "$3M", main: true },
            { n: "Tadeo Allende", p: "FW", r: 74, v: "$5M", main: false },
            { n: "Mateo Silvetti", p: "FW", r: 71, v: "$3M", main: false },
            { n: "David Ruiz", p: "FW", r: 70, v: "$2.5M", main: false },
            { n: "Dániel Pintér", p: "FW", r: 67, v: "$1.5M", main: false },
            { n: "Diego Rey", p: "FW", r: 64, v: "$800K", main: false },
            { n: "Lovens Delinois", p: "FW", r: 63, v: "$500K", main: false },
            { n: "David Ayala", p: "MF", r: 72, v: "$3M", main: false },
            { n: "Yannick Bright", p: "MF", r: 69, v: "$1.5M", main: false },
            { n: "Preston Plambeck", p: "MF", r: 66, v: "$1M", main: false },
            { n: "Alexander Shaw", p: "MF", r: 65, v: "$800K", main: false },
            { n: "Joseph Convers", p: "MF", r: 64, v: "$500K", main: false },
            { n: "Ian Urkidi", p: "MF", r: 63, v: "$500K", main: false },
            { n: "Micael", p: "DF", r: 73, v: "$3M", main: false },
            { n: "Ian Fray", p: "DF", r: 71, v: "$2M", main: false },
            { n: "Noah Allen", p: "DF", r: 70, v: "$2M", main: false },
            { n: "Santiago Morales", p: "DF", r: 68, v: "$1.5M", main: false },
            { n: "Cesar Abadia-Reda", p: "DF", r: 65, v: "$800K", main: false },
            { n: "Tyler Hall", p: "DF", r: 66, v: "$1M", main: false },
            { n: "Israel Boatwright", p: "DF", r: 65, v: "$800K", main: false },
            { n: "Fricio Caicedo", p: "DF", r: 64, v: "$600K", main: false },
            { n: "Daniel Sumalla", p: "DF", r: 62, v: "$400K", main: false },
            { n: "Rocco Ríos Novo", p: "GK", r: 71, v: "$2M", main: false },
            { n: "Luis Barraza", p: "GK", r: 68, v: "$1M", main: false }
        ]
    },

    // 20. Borussia Dortmund
    {
        name: "Borussia Dortmund",
        isWeak: false,
        squad: [
            { n: "Serhou Guirassy", p: "FW", r: 84, v: "$40M", main: true },
            { n: "Maximilian Beier", p: "FW", r: 80, v: "$30M", main: true },
            { n: "Fábio Silva", p: "FW", r: 77, v: "$20M", main: true },
            { n: "Marcel Sabitzer", p: "MF", r: 82, v: "$25M", main: true },
            { n: "Emre Can", p: "MF", r: 81, v: "$15M", main: true },
            { n: "Felix Nmecha", p: "MF", r: 78, v: "$25M", main: true },
            { n: "Ramy Bensebaini", p: "DF", r: 79, v: "$12M", main: true },
            { n: "Nico Schlotterbeck", p: "DF", r: 85, v: "$50M", main: true },
            { n: "Waldemar Anton", p: "DF", r: 81, v: "$25M", main: true },
            { n: "Julian Ryerson", p: "DF", r: 79, v: "$20M", main: true },
            { n: "Gregor Kobel", p: "GK", r: 87, v: "$40M", main: true },
            { n: "Samuele Inácio", p: "FW", r: 68, v: "$3M", main: false },
            { n: "Mathis Albert", p: "FW", r: 66, v: "$2M", main: false },
            { n: "Jobe Bellingham", p: "MF", r: 77, v: "$20M", main: false },
            { n: "Carney Chukwuemeka", p: "MF", r: 77, v: "$18M", main: false },
            { n: "Konstantinos Karetsas", p: "MF", r: 74, v: "$12M", main: false },
            { n: "Justin Lerma", p: "MF", r: 70, v: "$5M", main: false },
            { n: "Mussa Kaba", p: "MF", r: 65, v: "$1M", main: false },
            { n: "Daniel Svensson", p: "DF", r: 76, v: "$12M", main: false },
            { n: "Kouakou Gadou", p: "DF", r: 73, v: "$8M", main: false },
            { n: "Filippo Mané", p: "DF", r: 71, v: "$4M", main: false },
            { n: "Almugera Kabar", p: "DF", r: 70, v: "$3M", main: false },
            { n: "Kauã Prates", p: "DF", r: 65, v: "$1M", main: false },
            { n: "Luca Reggiani", p: "DF", r: 65, v: "$1M", main: false },
            { n: "Diant Ramaj", p: "GK", r: 77, v: "$12M", main: false },
            { n: "Patrick Drewes", p: "GK", r: 72, v: "$2M", main: false },
            { n: "Alexander Meyer", p: "GK", r: 74, v: "$2M", main: false },
            { n: "Silas Ostrzinski", p: "GK", r: 66, v: "$800K", main: false }
        ]
    }
];